version: '3'
services:
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=database
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=127.0.0.1